use_frameworks!
inhibit_all_warnings!

target 'WebIOPi_Example' do
  pod 'WebIOPi', :path => '../'

  target 'WebIOPi_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
