# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10
podfile: Example/Podfile
xcode_project: Example/WebIOPi.xcworkspace
xcode_scheme: WebIOPi-Example
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone XS
after_script: pod lib lint
